version: "3.3"

services:
  nodejs:
    image: node:10
    build:
      context: ./docker-containers/nodejs
      dockerfile: 'Dockerfile'
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    ports:
      - 3000:3000
      - 9229:9229
    command: npm start

networks:
  movie_net:
